## Config file
## github.com/vrmiguel/paradigm_shift_jekyll_theme

  # Site info
title: "Sacred Steps: Echoes of Nritya"
author: Ranjana Mahesh
description: >
  A journey of <strong class="dancer-name">Ranjana Mahesh</strong> through the grace and spirit of Indian classical dance.
email: 
phone: 
address: Nicolaus Copernicus University, Jurija Gagarina 11, 87-100 Toruń, Poland

  # Social media info -- If you don't want to use one of these, delete its respective line in footer.html

instagram: https://www.instagram.com/yourpagehere
